### ISSUE TITLE
Proposal: Make the core library a separate project

### ISSUE THREAD

**Issue by AnErrupTion** [TomatOrg/TomatOS#14]
Hello!

I find this project and its approach very interesting compared to others (such as Cosmos). What I've noticed as well is that you're creating a minimal core library which doesn't need a trillion native methods to implement to work (which is a nice thing).

So I'd share the proposal of making the core library its own separate project (just like you did with TinyDotNet). It could serve as a minimal CoreCLR library for either unsupported platfoms by .NET, or bare metal like here.

**Comment by Itay2805** [comment]
Its actually something I wanted to do for a long time, initially tinydotnet was part of this project as well, and as we wanted to add hosted supported we separated it, I just kinda forgot about also moving the corelib to be part of it. Putting it in another project on its own is also an idea but I am not sure how useful it will actually be, that is especially true for internal implementation details (like the System.Object layout), but I do admit not needing as many native functions for the core itself is indeed a nice addition (even tho admittedly its mostly because we just didn't add any of the IO subsystems, the rest are mostly copied from the corelib as-is).

**Comment by AnErrupTion** [comment]
> Putting it in another project on its own is also an idea but I am not sure how useful it will actually be, that is especially true for internal implementation details

In this case, it's better to be compliant on CoreCLR, so that implementations don't differ. As for the usefulness of it, well as I said, it could be used on bare metal but also on platforms that don't yet support .NET (with TinyDotNet + the small core library), though I guess it's even more of a niche use case since there aren't many platforms to port .NET to anymore.

> but I do admit not needing as many native functions for the core itself is indeed a nice addition

In my opinion a nice thing to do would be to move all native/extern functions to a separate folder (but not namespace) with the same file names etc... so that it would be easier to find them.

> admittedly its mostly because we just didn't add any of the IO subsystems

Yeah that too, but even then it probably just boils down to a couple of external methods, nothing out of the ordinary.

**Comment by Itay2805** [comment]
Being compliant with coreclr is a bit of a problem, because of inherit runtime differences (for example we are using a very different garbage collector in tinydotnet so the object header looks different, another example is reflection, tinydotnet uses C# reflection objects internally as well, so the layout is fixed, but that can also be fixed by doing the same as CoreCLR where Type has only virtual functions and RuntimeType or whatever it was is the actual instance). If we want to support multiple runtimes it would be possible to simply use the preprocessor (unless there is a nice way to choose which files to include based on compile target, ill admit I don't know the net core build system too much).

Btw do note that any extern method that we mark as Runtime instead of Native means that the JIT itself generates the code on the fly (we do that mostly for inlining, any function the JIT is aware of it can properly inline and what not, but those can easily be turned into native functions by the host).

Putting all native functions in their own place is actually a pretty cool idea, I might do that.

we specifically won't implement the IO subsystems (disk, networking etc) at all as part of the corelib, we want to keep it to the essentials of C# as much as possible (with the biggest subsystem probably being Task), but if we separate it properly I don't see why we couldn't add it as well as another assembly optionally.

**Comment by AnErrupTion** [comment]
> Being compliant with coreclr is a bit of a problem, because of inherit runtime differences

Perhaps a solution would be to make parts of the core library less dependent to the runtime, and have, for example, the Object class tied to the runtime (where basically you'd have to reimplement it if you change compiler and runtime, if any). So it would kind of be like an "extern" class.

> (unless there is a nice way to choose which files to include based on compile target, ill admit I don't know the net core build system too much).

C# supports conditional compilation, with ``#if`` etc... and the variables are defined in the csproj file.

> Btw do note that any extern method that we mark as Runtime instead of Native means that the JIT itself generates the code on the fly

I think CoreCLR achieves that with the ``[Intrinsic]`` internal attribute, you might want to check it out.

> we specifically won't implement the IO subsystems (disk, networking etc) at all as part of the corelib, we want to keep it to the essentials of C# as much as possible

I think the basics (like Stream for example) and I/O util classes (like Path) should be implemented (as they're kind of essential), however I think some classes like ``Console`` or ``File`` could have a minimal implementation, where most if not all functions (for File for example it would be ReadAllLines, WriteAllBytes, etc...) would be marked as external.

**Comment by Itay2805** [comment]
yeah by preprocessor I meant the `#if` statements.

I saw the Intrinsic and decided to use the MethodImpl attributes because they are parsed and placed nicely by the C# compiler, so it was easier to make it work without needing to do add a custom attribute support, but it essentially acts the same as the Intrinsic attribute :)

yeah that was my idea as well, Stream and Path can easily be implemented because they are utilities, just like collections and async. File, Console and anything networking will be external. We will probably have some of the more bloated stuff in a separate module (For example json serialization/deserialization) mostly for the corelib assembly to stay relatively self contained and not too bloated.

**Comment by AnErrupTion** [comment]
> mostly for the corelib assembly to stay relatively self contained and not too bloated.

That's a good idea, but...

> File, Console and anything networking will be external.

I think you should put those in separate assemblies, just so that we have some sort of implementation, even with most of it is external, because at least we can just implement the native methods and have it all working.

**Comment by Itay2805** [comment]
anyways given it is something I wanted to do for a long time I will probably take the weekend to at least separate it to another repo, not sure how much of the abstraction will be done right now mostly because we are focused on other stuff, will update this thread once its done 😄

**Comment by AnErrupTion** [comment]
Sure, take your time if you need to! After all it's a proposal :D

**Comment by Itay2805** [comment]
We did end up separging it so closing this issue :)
